### ISSUE TITLE
Review for automatic distribution

### ISSUE THREAD

**Issue by colemanw** [CiviCooP/org.civicoop.relationship2summary#1]
Hi Jaap. I tested out your relationship2summary extesion and it does what it says so I've marked it approved.

A nice-to-have would be for it to refresh that display when changes are made on the "Relationships" tab, without having to refresh the screen. Since you're doing it all with javascript anyway, that might be as simple as firing another api call and running the same code you've already written.

I did notice one "gotcha" which is that the api automatically limits results to 25. Given space constraints on the summary screen, that might not be a bad thing. But an improvement would be to limit further (maybe only 10?) with a "show more" link at the bottom if there are > 10 (do that with a "getcount" from smarty). The link could simply be javascript to take you over to the relationships tab (see how we do the same thing with the "Tags" link).

**Comment by jaapjansma** [comment]
@colemanw thanks for reporting the issue. I have fixed the limit and also the automatic refresh of the relationships.
